[selene]
# Selene Lua linter configuration for Xaster
# https://kampfkarren.github.io/selene/

std = "lua51+nvim"

[lints]
unused_variable = "warn"
undefined_variable = "error"
unscoped_variables = "warn"
incorrect_standard_library_use = "error"

[config]
# These globals are provided by Neovim
[vim]
any = "allow"

[describe]
any = "allow"

[it]
any = "allow"

[pcall_ok]
any = "allow"

[assert_eq]
any = "allow"
